name: Deploy to Cloud Run Job

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때 워크플로 실행

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  JOB_NAME: job-crawler-saramin

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |-
          docker build -f Dockerfile -t ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/my-repository/${{ env.JOB_NAME }}:${{ github.sha }} .
          docker push ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/my-repository/${{ env.JOB_NAME }}:${{ github.sha }}
      
      - name: Deploy Cloud Run Job
        run: |-
          gcloud run jobs deploy ${{ env.JOB_NAME }} \
            --image ${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/my-repository/${{ env.JOB_NAME }}:${{ github.sha }} \
            --region ${{ env.GCP_REGION }} \
            --set-env-vars=DB_HOST=${{ secrets.DB_HOST }},DB_USER=${{ secrets.DB_USER }},DB_PASSWORD=${{ secrets.DB_PASSWORD }},DB_PORT=${{ secrets.DB_PORT }} \
            --wait